// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWi0UI3Lc4yUi02lXMeQMt_p6NXNZjhHQ',
    appId: '1:714798624544:web:eb6df89716c36b2137f145',
    messagingSenderId: '714798624544',
    projectId: 'whatsapp-5bdec',
    authDomain: 'whatsapp-5bdec.firebaseapp.com',
    storageBucket: 'whatsapp-5bdec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rcRjNNqP8Bu7cjdEfRnfk_9SEOj3W4Y',
    appId: '1:714798624544:android:ae849103bfa7133337f145',
    messagingSenderId: '714798624544',
    projectId: 'whatsapp-5bdec',
    storageBucket: 'whatsapp-5bdec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsyDjxADBdqsp6DHEdaMsoyivFFZlgd_4',
    appId: '1:714798624544:ios:6e8032257e0809f937f145',
    messagingSenderId: '714798624544',
    projectId: 'whatsapp-5bdec',
    storageBucket: 'whatsapp-5bdec.appspot.com',
    iosClientId: '714798624544-u7noqi4sts6jfu8bs73kosjt4pnj80ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsyDjxADBdqsp6DHEdaMsoyivFFZlgd_4',
    appId: '1:714798624544:ios:6e8032257e0809f937f145',
    messagingSenderId: '714798624544',
    projectId: 'whatsapp-5bdec',
    storageBucket: 'whatsapp-5bdec.appspot.com',
    iosClientId: '714798624544-u7noqi4sts6jfu8bs73kosjt4pnj80ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
